// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crqkbippmyxagqpdvpbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycWtiaXBwbXl4YWdxcGR2cGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Nzc1MTEsImV4cCI6MjA2ODU1MzUxMX0.LGk96J3JH8-7_SH9uPpHr0Inve56vNIeMunFMGJJsVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});